name: Criar PR para Develop

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar Pull Request para Develop
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: 'develop'
          pr_title: 'Auto PR: ${{ github.ref_name }} para Develop'
          pr_body: 'Pull request criado automaticamente após novos commits na branch feature.'
          pr_labels: 'automerge'